name = "Ituz Survival"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a11455a1c346f249974c033142c405cdeffcd02aa86dc94a03824c4fa4c3c5e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
