name = "Ituz Survival"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29fae601960b2afe1333a4d699c240435647420bb8abb8f29561fcffac54797e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
